# Generated by Django 4.2.7 on 2023-11-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='genre',
            field=models.CharField(choices=[('fantasy', 'Fantasy'), ('action', 'Action'), ('horror', 'Horror'), ('romance', 'Romance'), ('science', 'Science Fiction'), ('comedy', 'Comedy'), ('drama', 'Drama')], max_length=150),
        ),
    ]
