# Generated by Django 4.2.7 on 2023-11-21 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_movies_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'verbose_name_plural': 'Movie'},
        ),
        migrations.AddField(
            model_name='movies',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
        migrations.AddField(
            model_name='movies',
            name='parental_rating',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movies',
            name='genre',
            field=models.CharField(choices=[('romance', 'Romance'), ('fantasy', 'Fantasy'), ('comedy', 'Comedy'), ('action', 'Action'), ('horror', 'Horror'), ('science', 'Science Fiction'), ('drama', 'Drama')], max_length=150),
        ),
    ]
