# Generated by Django 3.1 on 2023-12-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_movies_genre_movielist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='genre',
            field=models.CharField(choices=[('science', 'Science Fiction'), ('romance', 'Romance'), ('fantasy', 'Fantasy'), ('horror', 'Horror'), ('action', 'Action'), ('drama', 'Drama'), ('comedy', 'Comedy')], max_length=150),
        ),
        migrations.AlterField(
            model_name='movies',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
